// 维护一个主题列表(数组),向外导出以供使用

const themeList = [
  {
    id: 1,
    name: "光",
    value: "light",
    color: "#ffffff",
    textColor: "#000000",
    referenceColors: [
      { color1: "blue" },
      { color2: "dark" },
      { color3: "green" },
    ],
  },
  {
    id: 2,
    name: "暗",
    value: "dark",
    color: "#1c2229",
    textColor: "#ffffff",
    referenceColors: [
      { color1: "black" },
      { color2: "gray" },
      { color3: "red" },
    ],
  },
  {
    id: 3,
    name: "杯子蛋糕",
    value: "cupcake",
    color: "#faf7f5",
    textColor: "#000000",
    referenceColors: [
      { color1: "pink" },
      { color2: "yellow" },
      { color3: "purple" },
    ],
  },
  {
    id: 4,
    name: "蜜蜂",
    value: "bumblebee",
    color: "#ffffff",
    textColor: "#000000",
    referenceColors: [
      { color1: "yellow" },
      { color2: "black" },
      { color3: "white" },
    ],
  },
  {
    id: 5,
    name: "翡翠",
    value: "emerald",
    color: "#ffffff",
    textColor: "#000000",
    referenceColors: [
      { color1: "green" },
      { color2: "teal" },
      { color3: "white" },
    ],
  },
  {
    id: 6,
    name: "企业",
    value: "corporate",
    color: "#1e3a8a",
    textColor: "#ffffff",
    referenceColors: [
      { color1: "blue" },
      { color2: "gray" },
      { color3: "white" },
    ],
  },
  {
    id: 7,
    name: "合成波",
    value: "synthwave",
    color: "#1a103d",
    textColor: "#ffffff",
    referenceColors: [
      { color1: "purple" },
      { color2: "pink" },
      { color3: "blue" },
    ],
  },
  {
    id: 8,
    name: "复古",
    value: "retro",
    color: "#ede4cc",
    textColor: "#000000",
    referenceColors: [
      { color1: "orange" },
      { color2: "brown" },
      { color3: "cream" },
    ],
  },
  {
    id: 9,
    name: "赛博朋克",
    value: "cyberpunk",
    color: "#fff347",
    textColor: "#000000",
    referenceColors: [
      { color1: "neon green" },
      { color2: "pink" },
      { color3: "blue" },
    ],
  },
  {
    id: 10,
    name: "情人节",
    value: "valentine",
    color: "#fae6f4",
    textColor: "#000000",
    referenceColors: [
      { color1: "red" },
      { color2: "pink" },
      { color3: "white" },
    ],
  },
  {
    id: 11,
    name: "万圣节",
    value: "halloween",
    color: "#212121",
    textColor: "#e8e6e6",
    referenceColors: [
      { color1: "orange" },
      { color2: "black" },
      { color3: "purple" },
    ],
  },
  {
    id: 12,
    name: "花园",
    value: "garden",
    color: "#e8e6e6",
    textColor: "#000000",
    referenceColors: [
      { color1: "green" },
      { color2: "pink" },
      { color3: "yellow" },
    ],
  },
  {
    id: 13,
    name: "森林",
    value: "forest",
    color: "#171212",
    textColor: "#e8e6e6",
    referenceColors: [
      { color1: "darkgreen" },
      { color2: "brown" },
      { color3: "beige" },
    ],
  },
  {
    id: 14,
    name: "水",
    value: "aqua",
    color: "#335ba6",
    textColor: "#000000",
    referenceColors: [
      { color1: "cyan" },
      { color2: "blue" },
      { color3: "white" },
    ],
  },
  {
    id: 15,
    name: "低保真",
    value: "lofi",
    color: "#ffffff",
    textColor: "#000000",
    referenceColors: [
      { color1: "brown" },
      { color2: "cream" },
      { color3: "green" },
    ],
  },
  {
    id: 16,
    name: "粉彩",
    value: "pastel",
    color: "#ffffff",
    textColor: "#000000",
    referenceColors: [
      { color1: "lightpink" },
      { color2: "lightblue" },
      { color3: "lightgreen" },
    ],
  },
  {
    id: 17,
    name: "幻想",
    value: "fantasy",
    color: "#ffffff",
    textColor: "#000000",
    referenceColors: [
      { color1: "purple" },
      { color2: "gold" },
      { color3: "blue" },
    ],
  },
  {
    id: 18,
    name: "线框",
    value: "wireframe",
    color: "#d3d3d3",
    textColor: "#000000",
    referenceColors: [
      { color1: "gray" },
      { color2: "white" },
      { color3: "black" },
    ],
  },
  {
    id: 19,
    name: "黑色",
    value: "black",
    color: "#000000",
    textColor: "#ffffff",
    referenceColors: [
      { color1: "black" },
      { color2: "darkgray" },
      { color3: "white" },
    ],
  },
  {
    id: 20,
    name: "奢华",
    value: "luxury",
    color: "#ffd700",
    textColor: "#ffffff",
    referenceColors: [
      { color1: "gold" },
      { color2: "black" },
      { color3: "white" },
    ],
  },
  {
    id: 21,
    name: "德拉库拉",
    value: "dracula",
    color: "#800080",
    textColor: "#ffffff",
    referenceColors: [
      { color1: "purple" },
      { color2: "red" },
      { color3: "black" },
    ],
  },
  {
    id: 22,
    name: "CMYK",
    value: "cmyk",
    color: "#00bfff",
    textColor: "#ffffff",
    referenceColors: [
      { color1: "cyan" },
      { color2: "magenta" },
      { color3: "yellow" },
    ],
  },
  {
    id: 23,
    name: "秋天",
    value: "autumn",
    color: "#ff8c00",
    textColor: "#ffffff",
    referenceColors: [
      { color1: "orange" },
      { color2: "brown" },
      { color3: "yellow" },
    ],
  },
  {
    id: 24,
    name: "商业",
    value: "business",
    color: "#1e3a8a",
    textColor: "#000000",
    referenceColors: [
      { color1: "navy" },
      { color2: "gray" },
      { color3: "white" },
    ],
  },
  {
    id: 25,
    name: "酸",
    value: "acid",
    color: "#fafafa",
    textColor: "#000000",
    referenceColors: [
      { color1: "lime" },
      { color2: "purple" },
      { color3: "black" },
    ],
  },
  {
    id: 26,
    name: "柠檬水",
    value: "lemonade",
    color: "#f7fced",
    textColor: "#000000",
    referenceColors: [
      { color1: "yellow" },
      { color2: "pink" },
      { color3: "white" },
    ],
  },
  {
    id: 27,
    name: "夜晚",
    value: "night",
    color: "#001f3f",
    textColor: "#ffffff",
    referenceColors: [
      { color1: "darkblue" },
      { color2: "black" },
      { color3: "gray" },
    ],
  },
  {
    id: 28,
    name: "咖啡",
    value: "coffee",
    color: "#6f4c3e",
    textColor: "#ffffff",
    referenceColors: [
      { color1: "brown" },
      { color2: "cream" },
      { color3: "darkbrown" },
    ],
  },
  {
    id: 29,
    name: "冬天",
    value: "winter",
    color: "#add8e6",
    textColor: "#000000",
    referenceColors: [
      { color1: "lightblue" },
      { color2: "white" },
      { color3: "gray" },
    ],
  },
  {
    id: 30,
    name: "昏暗",
    value: "dim",
    color: "#696969",
    textColor: "#ffffff",
    referenceColors: [
      { color1: "darkgray" },
      { color2: "black" },
      { color3: "purple" },
    ],
  },
  {
    id: 31,
    name: "北欧",
    value: "nord",
    color: "#edf0f5",
    textColor: "#000000",
    referenceColors: [
      { color1: "blue" },
      { color2: "white" },
      { color3: "gray" },
    ],
  },
  {
    id: 32,
    name: "日落",
    value: "sunset",
    color: "#121b21",
    textColor: "#ffffff",
    referenceColors: [
      { color1: "orange" },
      { color2: "pink" },
      { color3: "purple" },
    ],
  },
];

export default themeList;
